"""
Django settings for gif project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path

PROJECT_NAME = 'gif'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-55w_ylt*+bhszux=5*(1x=84)fv4-yb=!rgzd0q2y@9d2muwx3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'sorl.thumbnail',
    'widget_tweaks',

    'core',
    'apps.jobs',
    'apps.projects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "{0}_db".format(PROJECT_NAME),
        'USER': "{0}".format(PROJECT_NAME),
        'PASSWORD': "2+PJh#&?",
        'HOST': "127.0.0.1",
        'PORT': "5432",
        'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_L10N = False

USE_TZ = True

USE_HTTPS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'assets/%s' % PROJECT_NAME)

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Logging Settings
LOGGING_ROOT = os.path.join(BASE_DIR, 'logs')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[%(asctime)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'verbose': {
            'format': '%(levelname)s - [%(asctime)s] [%(name)s:%(lineno)s] - %(module)s - \
                %(process)d - %(thread)d - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s - [%(name)s:%(lineno)s] - %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'log_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_ROOT, 'error.log'),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 2,
            'formatter': 'verbose',
            # Without this, RotatingFileHandler falls back to the OS's
            # locale-preferred encoding, which on Windows is cp1252 - unable
            # to represent most non-Latin1 characters. Any log message
            # containing one (e.g. a dumped Facebook page's visible text,
            # which can include arbitrary Unicode from account names, emoji,
            # or foreign-language UI text) then raises UnicodeEncodeError
            # inside logging's own emit(), silently discarding that log
            # record entirely instead of writing it.
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['mail_admins', 'log_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        '%s' % PROJECT_NAME: {
            'handlers': ['console', 'mail_admins', 'log_file'],
            'level': 'DEBUG',
        },
    },
    # Root logger: catches every other module's logger (e.g.
    # `logging.getLogger(__name__)` in core/automation/*.py, apps/*.py),
    # since those module paths (e.g. "core.automation.facebook_recovery")
    # are NOT children of the "pull_data" logger above and would otherwise
    # only fall back to Python's silent last-resort handler.
    'root': {
        'handlers': ['console', 'log_file'],
        'level': 'INFO',
    },
}

# Detection Settings
# Backends are swappable so the pipeline can run without the multi-gigabyte
# ML stack installed. Switch to 'yolo' / 'paddle' once those are available.
DETECTION_OBJECT_BACKEND = 'yolo'
DETECTION_TEXT_BACKEND = 'paddle'
DETECTION_MIN_CONFIDENCE = 0.15
DETECTION_IOU_THRESHOLD = 0.9

YOLO_MODEL = os.path.join(BASE_DIR, 'ml_models', 'yolov8s.pt')
PADDLEOCR_LANG = 'en'

# paddlepaddle 3.3.1 on CPU crashes inside the oneDNN text-detection kernel
# with "ConvertPirAttribute2RuntimeAttribute not support". Running without
# oneDNN avoids it at a small speed cost.
PADDLEOCR_ENABLE_MKLDNN = False

# PaddleOCR 3.x defaults to limit_type='min' and limit_side_len=64, which
# shrinks a 1280px promo down to 64px before text detection. Boxes then
# come back in the right neighbourhood but miss the glyphs. Detect at the
# same size we preprocess to, and skip document unwarp/orientation so the
# polygons stay in the input image's coordinate space.
PADDLEOCR_DET_LIMIT_TYPE = 'max'
PADDLEOCR_DET_LIMIT_SIDE_LEN = 1280
PADDLEOCR_DET_UNCLIP_RATIO = 1.8
PADDLEOCR_USE_DOC_ORIENTATION = False
PADDLEOCR_USE_DOC_UNWARPING = False
PADDLEOCR_USE_TEXTLINE_ORIENTATION = False

# GIF generation. Boxes are normalised, so downscaling the source here only
# affects output file size, not the selected regions.
GIF_MAX_SIDE = 720
GIF_FRAME_COUNT = 32
GIF_DURATION_MS = 50
GIF_GLOW = 0.35
GIF_SHINE_WIDTH = 0.18
GIF_FEATHER = 10

DATA_UPLOAD_MAX_NUMBER_FIELDS = None
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 # 10MB