# Generated by Django 6.1 on 2026-08-20 08:07

import apps.jobs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Processing', 'processing'), ('completed', 'Completed'), ('Failed', 'failed')], default='pending', max_length=255, verbose_name='Status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Task ID')),
                ('gif_file', models.FileField(blank=True, null=True, upload_to=apps.jobs.models.generate_gif_file, verbose_name='GIF File')),
                ('frame_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frame Count')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='projects.project', verbose_name='Project')),
                ('selected_objects', models.ManyToManyField(related_name='animation_jobs', to='projects.detectionobject', verbose_name='Detection Objects')),
            ],
            options={
                'verbose_name': 'Animation Job',
                'verbose_name_plural': 'Animation Jobs',
                'ordering': ['-created'],
                'unique_together': {('project', 'version')},
            },
        ),
    ]
