# Generated by Django 6.1 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_animationjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationjob',
            name='animation_type',
            field=models.CharField(
                choices=[
                    ('shine', 'Gold shine sweep'),
                    ('glow', 'Soft glow'),
                    ('gold_pulse', 'Gold colour pulse'),
                    ('breathe', 'Subtle breathe'),
                    ('float', 'Idle float'),
                    ('sparkle', 'Sparkle'),
                    ('fade', 'Fade pulse'),
                    ('zoom', 'Slow zoom'),
                    ('rim', 'Rim light'),
                    ('flicker', 'Gold flicker'),
                ],
                default='shine',
                max_length=32,
                verbose_name='Animation Type',
            ),
        ),
    ]
