# Generated by Django 6.1 on 2026-08-21

from django.db import migrations, models


def copy_animation_type(apps, schema_editor):
    AnimationJob = apps.get_model('jobs', 'AnimationJob')
    for job in AnimationJob.objects.all():
        value = getattr(job, 'animation_type', None) or 'shine'
        job.animation_types = [value]
        job.save(update_fields=['animation_types'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_animationjob_animation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationjob',
            name='animation_types',
            field=models.JSONField(blank=True, default=list, help_text='One or more effect keys applied in order.', verbose_name='Animation Types'),
        ),
        migrations.AddField(
            model_name='animationjob',
            name='regions',
            field=models.JSONField(blank=True, default=list, help_text='Adjusted boxes used for GIF generation (normalised 0-1).', verbose_name='Regions'),
        ),
        migrations.RunPython(copy_animation_type, noop),
        migrations.RemoveField(
            model_name='animationjob',
            name='animation_type',
        ),
    ]
