# Generated by Django 6.1 on 2026-08-21

import apps.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_regions_and_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationjob',
            name='video_file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.jobs.models.generate_video_file,
                verbose_name='Preview Video',
            ),
        ),
    ]
