# Generated by Django 6.1 on 2026-08-20 08:07

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('project_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Project ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.projects.models.generate_project_image, verbose_name='Image')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='DetectionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Label')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Confidence')),
                ('source', models.CharField(blank=True, choices=[('yolo', 'Yolo'), ('ocr', 'OCR')], max_length=255, null=True, verbose_name='Source')),
                ('x', models.FloatField(default=0.0, verbose_name='X')),
                ('y', models.FloatField(default=0.0, verbose_name='Y')),
                ('width', models.FloatField(default=0.0, verbose_name='Width')),
                ('height', models.FloatField(default=0.0, verbose_name='Height')),
                ('text_content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text Content')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Detection Object',
                'verbose_name_plural': 'Detection Objects',
            },
        ),
    ]
