# Generated by Django 6.1 on 2026-08-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionobject',
            name='source',
            field=models.CharField(blank=True, choices=[('yolo', 'Yolo'), ('ocr', 'OCR'), ('manual', 'Manual')], max_length=255, null=True, verbose_name='Source'),
        ),
    ]
