# Generated by Django 6.1 on 2026-08-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_detectionobject_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionobject',
            name='source',
            field=models.CharField(blank=True, choices=[('yolo', 'Yolo'), ('ocr', 'OCR'), ('manual', 'Manual'), ('card', 'Card'), ('button', 'Button'), ('title', 'Title')], max_length=255, null=True, verbose_name='Source'),
        ),
    ]
